secrets:
  SECRET_KEY:
    file: docker/secrets/secret_key.txt
  DB_PASSWORD:
    file: docker/secrets/db_password.txt
  GOOGLE_API_KEY:
    file: docker/secrets/google_api_key.txt

networks:
  default:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:4.1-alpine
    networks:
      - default
    volumes:
      - ${VOLUME_PATH}/rabbitmq:/var/lib/rabbitmq
    # override hostname to prevent reinitialization of data
    # on container delete/init cycle.
    #   Refs: https://github.com/docker-library/rabbitmq/issues/106#issuecomment-241882358
    hostname: 'rabbitmq-staging'

  app:
    image: ghcr.io/osu-cass/oregoninvasiveshotline:develop
    env_file:
      - .env.staging
    environment:
      - APP_SERVICE=wsgi
    networks:
      - default
    ports:
      - ${APP_PORT:-8001}:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUME_PATH}/media:/media
      - ${VOLUME_PATH}/static:/static
      - ./:/app
    depends_on:
      - rabbitmq
    secrets:
      - SECRET_KEY
      - DB_PASSWORD
      - GOOGLE_API_KEY
    user: '${USER_ID}'

  celery:
    image: ghcr.io/osu-cass/oregoninvasiveshotline:develop
    env_file:
      - .env.staging
    environment:
      - APP_SERVICE=celery
    networks:
      - default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUME_PATH}/media:/media
      - ./:/app
    depends_on:
      - app
    secrets:
      - SECRET_KEY
      - DB_PASSWORD
    user: '${USER_ID}'
