secrets:
  SecretKey:
    file: docker/secrets/secret_key.txt
  DBPassword:
    file: docker/secrets/db_password.txt
  GOOGLE_API_KEY:
    file: docker/secrets/google_api_key.txt

networks:
  default:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:4.1-alpine
    networks:
      - default
    volumes:
      - ${VOLUME_PATH}/rabbitmq:/var/lib/rabbitmq
    # override hostname to prevent reinitialization of data
    # on container delete/init cycle.
    #   Refs: https://github.com/docker-library/rabbitmq/issues/106#issuecomment-241882358
    hostname: 'rabbitmq-dev'

  bootstrap:
    image: ghcr.io/osu-cass/oregoninvasiveshotline:latest
    environment:
      - EMCEE_CMD_ENV=docker
      - APP_SERVICE=bootstrap
    networks:
      - default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUME_PATH}/media:/media
      - ${VOLUME_PATH}/static:/static
      - ./:/app
    secrets:
      - SecretKey
      - DBPassword
    user: '${USER_ID}'

  app:
    image: ghcr.io/osu-cass/oregoninvasiveshotline:latest
    environment:
      - EMCEE_CMD_ENV=docker
      - APP_SERVICE=wsgi
      - APP_ENVIRONMENT=production
    networks:
      - default
    ports:
      - 8000:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUME_PATH}/media:/media
      - ${VOLUME_PATH}/static:/static
      - ./:/app
    depends_on:
      - rabbitmq
    secrets:
      - SecretKey
      - DBPassword
      - GOOGLE_API_KEY
    user: '${USER_ID}'

  celery:
    image: ghcr.io/osu-cass/oregoninvasiveshotline:latest
    environment:
      - EMCEE_CMD_ENV=docker
      - APP_SERVICE=celery
    networks:
      - default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUME_PATH}/media:/media
      - ./:/app
    depends_on:
      - app
    secrets:
      - SecretKey
      - DBPassword
    user: '${USER_ID}'
