blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/osu-cass/oregoninvasiveshotline/blob/main/README.md
    about: Read the project documentation and setup instructions
